org.gradle.jvmargs=-Xmx1G
org.gradle.caching=false
org.gradle.configuration-cache=false

# Auto install java25 if not found
org.gradle.java.installations.auto-download=true
org.gradle.java.installations.auto-detect=true

# Plugin Metadata
plugin_group=LakeCountryGames
plugin_name=Hytech
plugin_description=Hytech Power and systems hytale mod! By LakeCountryGames
plugin_author=Laophy
plugin_website=https://lakecountrygames.com
plugin_main_entrypoint=com.LakeCountryGames.plugin.Hytech
server_version=*
